### ISSUE TITLE
[bug]: The application "Ball.app" can't be opened.

### ISSUE THREAD

**Issue by Bellisario** [nate-parrott/ball#1]
When trying to run the executable downloaded from GitHub releases, I get the following message:

<img width="296" alt="Screenshot 2024-06-22 at 11 05 32" src="https://github.com/nate-parrott/ball/assets/72039923/8bed8ab9-934e-449a-be8e-4cd54ea3061c">

Investigating inside the app "Package Contents" I discovered that the app executable has no executable permission (it's considered a "Document", not a "Unix Executable File"), so that's why it's unable to run:

<img width="747" alt="Screenshot 2024-06-22 at 11 09 11" src="https://github.com/nate-parrott/ball/assets/72039923/f0230866-e704-4c0c-b94c-2eabea8a736e">

---

To manually fix this issue, I had to add the executable permission with:

```bash
chmod 755 /Applications/Ball.app/Contents/MacOS/Ball
```

**Comment by nate-parrott** [comment]
should be fixed!
