### ISSUE TITLE
JIRA Integration

### ISSUE THREAD

**Issue by hugows** [nate-parrott/ball#7]
Use Cases:
	1.	Random Task Generator:
	▪	Click the ball to get a randomly assigned task from your JIRA backlog.
	2.	Quick Task Overview:
	▪	Hover over the ball to see a snapshot of your current JIRA issues, including due dates and statuses.
	3.	Task Assignment:
	▪	Drag the ball to a colleague's avatar to assign them a new task or share project status updates.
	4.	Break Timer:
	▪	The ball can remind you to take breaks, enhancing productivity and reducing burnout. After completing a task, give the ball a bounce to trigger a five-minute break timer.

**Comment by jonathan-bird** [comment]
Alternatively, click the ball to **delete** random JIRA tickets from the backlog...
